state_with_vol: false
env_data: "env_data/sp500_volpct.csv"
seed_number: 42
heuristic_search: false
year_range:
  - 2010
  - 2025
gamma: 0.99
warmup_steps: 10000

train:
  max_len: 20
  batch_size: 64
  hidden_size: 128
  epochs: 200
  target_return: 5

opt:
  lr: 1e-4
  weight_decay: 1e-4


